### PR TITLE
Create fa-IR.lng

### PR DESCRIPTION
**Pull request by motarjemjavan**
Please merge Persian translation. :)

### CODE REVIEW

**Comment by mariobalanica** [comment]
Thanks for working on this!

As a native speaker, does the UI look okay to you with the LTR layout? 
I'm asking because I don't currently plan to add RTL support, as there's little to no demand for it. In this case, wouldn't the English translation look more "natural" to Persians?

**Comment by motarjemjavan** [comment]
Dear Mario,

I work in the marketing department of an IT company in Tehran.
I have noticed that most of the developers prefer their native language,
Persian.

Despite my curiosity, I do not have the hardware, but I have heard that one
of my friends uses it to set up a mining rig with Raspberry. It is why I
have been interested to know more and searched GitHub and found WoR.

I hope you add the RTL languages in the future.
You may count on me for further support of the language.

Best Regards,
Hossein
___________________________________________________
*Hossein M. Mohammadi*
English to Persian (Farsi) Translation and Language Services by a Native
Linguist.
My Services are Translation, Localization, Copy-writing, Voice-over,
Proofreading, etc.
Skype: motarjemjavan  |  ***@***.***

**** Print Less, Go Green, Love Earth!*


*#StaySafe*

**Comment by mariobalanica** [comment]
This is how the UI would currently look like with the Persian translation:
image
image

And this is how it looks in English:
image

Which one do you prefer? Doesn't the LTR layout + Persian language combo look weird?

**Comment by motarjemjavan** [comment]
Dear Mario,

Text in Persian should be RTL. Your screenshot is LTR.
See the attached screenshot please.


Best Regards,
Hossein

**Comment by mariobalanica** [comment]
I know, but as I've said above, implementing RTL support is low priority at best. Given this situation, do you agree that English would be a better choice for now?

**Comment by motarjemjavan** [comment]
Dear Mario,

I think if the RTL is not the priority of the project, it is better to see
English version.

That way the translation is not a help to people.

I understand your situation and thank for your kind consideration. 😉🌹

Best Regards,
Hossein

**Comment by mariobalanica** [comment]
I'll merge this in a separate branch for the time being.
Thanks.

**Pull request merged**
